name: Build

on:
  workflow_dispatch:
  push:  
    branches: 
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref_name }}
      
jobs: 
  build:   
    runs-on: ubuntu-latest
    name: build / ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v3
      - uses: habitus-health/pipelines/docker@main
        with:     
          password: ${{ secrets.AAD_GITHUB_CLIENT_SECRET }}
          username: ${{ vars.AAD_GITHUB_CLIENT_ID }}       
          build: ${{ matrix.dockerfile }}
          image: ${{ matrix.image }}
    strategy:
      matrix:
        include: 
          # Account
          - dockerfile: .
            image: radius-server
          
